"""added refresh token

Revision ID: 72176b62981c
Revises: 4fcec04d39e3
Create Date: 2025-10-13 19:17:14.475301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72176b62981c'
down_revision: Union[str, Sequence[str], None] = '4fcec04d39e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema = None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    
    with op.batch_alter_table('expenses', schema = None) as batch_op:
        batch_op.create_foreign_key('fk_expenses_user_id_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema = None) as batch_op:
        batch_op.drop_constraint('fk_expenses_user_id_users', type_='foreignkey')
    
    with op.batch_alter_table('users', schema = None) as batch_op:
        batch_op.drop_column('refresh_token_expires_at')
        batch_op.drop_column('refresh_token')
    # ### end Alembic commands ###
