name: ExpenseTracker - FastAPI Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: CheckOut repository
              uses: actions/checkout@v5
              
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        
            - name: Run tests
              run:
                pytest -v
        